version: '3.7'

services:
  eshop:
    container_name: eshop.dev.local
    build:
      context: .
      dockerfile: src/EShop.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - ASPNETCORE_ENVIRONMENT=${DEPLOYMENT_TARGET}
    ports:
      - "${APPLICATION_PORT}:443"
    networks:
      - outside
networks:
  outside:
    external: true
    name: ${OVERLAY_NAME}